In [2]:
import pandas as pd

## PIB per cápita  
 
El PIB per cápita es un indicador económico que relaciona el valor total de la producción de una región con su población, y se utiliza como aproximación al nivel medio de riqueza y capacidad económica de los territorios. En este análisis se empleará como variable base para comparar comunidades autónomas y estudiar su evolución temporal, sirviendo como punto de partida para el análisis del resto de indicadores socioeconómicos.

[Bibliografia](https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736167628&menu=resultados&idp=1254735576581#_tabs-1254736158133)

In [5]:
df = pd.read_excel("../../data/raw/pr_cre_pr.xlsx",sheet_name="Tabla_2")

In [7]:
df.head()

,Comunidad Autónoma,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,ANDALUCÍA,11882,12799,13617,14593,15561,16564,17589,18504,18638,...,17458,17865,18691,19291,19744,17772,19591,21532,23199,24566
1,ARAGÓN,17016,18231,19492,20570,21676,22932,24484,26080,26519,...,25185,26243,27357,28281,29043,27003,29144,32707,34484,36446
2,"ASTURIAS, PRINCIPADO DE",13279,14340,15188,16039,17055,18482,20059,21416,21987,...,20497,20913,21897,22651,23220,21069,23446,26552,28136,29658
3,"BALEARS, ILLES",20045,21350,21837,22109,22975,24054,25259,26092,26377,...,25732,26922,28001,28906,29458,22611,25807,31029,33922,36011
4,CANARIAS,14985,16143,16815,17480,17980,18708,19484,20276,20476,...,18881,19450,20296,20853,21159,17239,19021,22218,24337,25925

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Comunidad Autónoma  19 non-null     object
 1   2000                19 non-null     int64
 2   2001                19 non-null     int64
 3   2002                19 non-null     int64
 4   2003                19 non-null     int64
 5   2004                19 non-null     int64
 6   2005                19 non-null     int64
 7   2006                19 non-null     int64
 8   2007                19 non-null     int64
 9   2008                19 non-null     int64
 10  2009                19 non-null     int64
 11  2010                19 non-null     int64
 12  2011                19 non-null     int64
 13  2012                19 non-null     int64
 14  2013                19 non-null     int64
 15  2014                19 non-null     int64
 16  2015                19 non-null     int64
 17  2016                19 non-null     int64
 18  2017                19 non-null     int64
 19  2018                19 non-null     int64
 20  2019                19 non-null     int64
 21  2020                19 non-null     int64
 22  2021                19 non-null     int64
 23  2022                19 non-null     int64
 24  2023                19 non-null     int64
 25  2024                19 non-null     int64
dtypes: int64(25), object(1)
memory usage: 4.0+ KB

## Renta disponible bruta de los hogares (per capita)

La renta disponible bruta de los hogares refleja el ingreso efectivo del que disponen los hogares para el consumo y el ahorro, una vez descontados impuestos y cotizaciones sociales y sumadas las transferencias recibidas. Este indicador resulta especialmente relevante para complementar el PIB per cápita, ya que ofrece una aproximación más directa al poder adquisitivo real de la población en cada comunidad autónoma.  

[Bibliografia](https://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736167628&menu=resultados&idp=1254735576581#_tabs-1254736195584)

In [9]:
df = pd.read_excel("../../data/raw/rentahogd24.xlsx",sheet_name="Tabla_2")

In [10]:
df.head()

,Comunidad Autónoma,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,ANDALUCÍA,8191,8776,9165,9765,10196,10688,11173,11508,11951,...,11100,11137,11688,11831,12177,12733,13199,13104,13801,14332
1,ARAGÓN,11098,11869,12547,13224,13635,14293,15043,15547,16062,...,15127,15032,15511,15998,16492,16896,17585,17380,17925,19066
2,"ASTURIAS, PRINCIPADO DE",9644,10410,11040,11717,12332,13261,14241,15082,15480,...,14316,14350,14955,15091,15673,16168,16773,16705,17413,18614
3,"BALEARS, ILLES",12919,13792,13988,14196,14732,15078,15474,15582,15910,...,14496,14655,15418,16074,16344,16857,17529,15616,16810,18339
4,CANARIAS,10008,10701,11142,11569,11806,12122,12396,12664,12875,...,11960,11915,12458,12830,13322,13519,13987,13030,13986,14702

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Comunidad Autónoma  19 non-null     object
 1   2000                19 non-null     int64
 2   2001                19 non-null     int64
 3   2002                19 non-null     int64
 4   2003                19 non-null     int64
 5   2004                19 non-null     int64
 6   2005                19 non-null     int64
 7   2006                19 non-null     int64
 8   2007                19 non-null     int64
 9   2008                19 non-null     int64
 10  2009                19 non-null     int64
 11  2010                19 non-null     int64
 12  2011                19 non-null     int64
 13  2012                19 non-null     int64
 14  2013                19 non-null     int64
 15  2014                19 non-null     int64
 16  2015                19 non-null     int64
 17  2016                19 non-null     int64
 18  2017                19 non-null     int64
 19  2018                19 non-null     int64
 20  2019                19 non-null     int64
 21  2020                19 non-null     int64
 22  2021                19 non-null     int64
 23  2022                19 non-null     int64
dtypes: int64(23), object(1)
memory usage: 3.7+ KB

## Población

Se incorpora la población por comunidad autónoma y año con el objetivo de contextualizar los indicadores económicos y permitir análisis adicionales, como la validación de valores per cápita y el estudio de la evolución demográfica en relación con la renta y el PIB.  

[Bibliografia](https://www.ine.es/jaxi/Tabla.htm?path=/t20/e245/p08/l0/&file=02003.px&L=0)

In [15]:
df = pd.read_csv("../../data/raw/poblacion.csv", sep= ";", dtype=str)

In [16]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 459000 entries, 0 to 458999
Data columns (total 7 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Total Nacional                    459000 non-null  object
 1   Comunidades y Ciudades Autónomas  436050 non-null  object
 2   Edad (año a año)                  459000 non-null  object
 3   Españoles/Extranjeros             459000 non-null  object
 4   Sexo                              459000 non-null  object
 5   Periodo                           459000 non-null  object
 6   Total                             459000 non-null  object
dtypes: object(7)
memory usage: 24.5+ MB

,Total Nacional,Comunidades y Ciudades Autónomas,Edad (año a año),Españoles/Extranjeros,Sexo,Periodo,Total
0,Total Nacional,NaN,TOTAL EDADES,TOTAL,Ambos sexos,2022,47.475.420
1,Total Nacional,NaN,TOTAL EDADES,TOTAL,Ambos sexos,2021,47.385.107
2,Total Nacional,NaN,TOTAL EDADES,TOTAL,Ambos sexos,2020,47.450.795
3,Total Nacional,NaN,TOTAL EDADES,TOTAL,Ambos sexos,2019,47.026.208
4,Total Nacional,NaN,TOTAL EDADES,TOTAL,Ambos sexos,2018,46.722.980

## Población con gasto elevado en vivienda

Este indicador mide el porcentaje de población que destina una proporción elevada de sus ingresos al gasto en vivienda, y se utiliza como aproximación a la **presión económica asociada al acceso y mantenimiento de la vivienda**. Su incorporación permite complementar los indicadores de renta y precios, aportando una dimensión directa del esfuerzo económico de los hogares por comunidad autónoma.

[Bibliografia](https://www.ine.es/jaxiT3/Tabla.htm?t=69497&L=0)

In [20]:
df = pd.read_csv("../../data/raw/gasto_elevado_vivienda.csv", sep=";")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Comunidad autónoma  340 non-null    object
 1   Periodo             340 non-null    int64
 2   Total               340 non-null    object
dtypes: int64(1), object(2)
memory usage: 8.1+ KB

  Comunidad autónoma  Periodo Total
0     Total Nacional     2024   7,8
1     Total Nacional     2023   8,2
2     Total Nacional     2022   9,2
3     Total Nacional     2021   9,9
4     Total Nacional     2020   8,2

## Población con falta de espacio en la vivienda

Este indicador (en %) estima la proporción de población que vive en viviendas con **hacinamiento o espacio insuficiente**. Se incorpora para añadir una dimensión material de la calidad de vida vinculada a las condiciones habitacionales, complementando renta, IPC y presión de gasto en vivienda.

[Bibliografia](https://www.ine.es/jaxiT3/Tabla.htm?t=69488&L=0)

In [19]:
df = pd.read_csv("../../data/raw/falta_espacio_vivienda.csv", sep= ";")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Comunidad autónoma  420 non-null    object
 1   Periodo             420 non-null    int64
 2   Total               420 non-null    object
dtypes: int64(1), object(2)
memory usage: 10.0+ KB

  Comunidad autónoma  Periodo Total
0     Total Nacional     2024   9,1
1     Total Nacional     2023   7,6
2     Total Nacional     2022   6,6
3     Total Nacional     2021   6,4
4     Total Nacional     2020   7,6

## Retrasos en los pagos

Este indicador mide el porcentaje de población que ha experimentado **retrasos en el pago de gastos básicos** (como vivienda, suministros o préstamos), y se utiliza como proxy de **vulnerabilidad y seguridad económica**. Su incorporación permite complementar los indicadores de renta y condiciones materiales, aportando una medida directa de dificultades financieras de los hogares por comunidad autónoma.

[Bibliografia](https://www.ine.es/jaxiT3/Tabla.htm?t=69536&L=0)

In [21]:
df = pd.read_csv("../../data/raw/Retrasos_pagos.csv", sep= ";")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Comunidad autónoma  420 non-null    object
 1   Periodo             420 non-null    int64
 2   Total               420 non-null    object
dtypes: int64(1), object(2)
memory usage: 10.0+ KB

  Comunidad autónoma  Periodo Total
0     Total Nacional     2024  14,2
1     Total Nacional     2023  13,6
2     Total Nacional     2022  13,2
3     Total Nacional     2021  14,4
4     Total Nacional     2020  13,5

## Renta media y mediana por unidad de consumo

Este indicador recoge la **renta media y la renta mediana por unidad de consumo**, permitiendo aproximar el nivel de ingresos de los hogares y su distribución. La comparación entre ambos valores resulta útil para identificar **asimetrías y posibles desigualdades internas** dentro de cada comunidad autónoma, complementando la renta disponible bruta y el PIB per cápita.

[Bibliografia](https://www.ine.es/jaxiT3/Tabla.htm?t=68338&L=0)

In [22]:
df = pd.read_csv("../../data/raw/Renta_media_mediana.csv", sep= ";")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 680 entries, 0 to 679
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Renta media y mediana  680 non-null    object
 1   Comunidad autónoma     680 non-null    object
 2   Periodo                680 non-null    int64
 3   Total                  680 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 21.4+ KB

               Renta media y mediana Comunidad autónoma  Periodo   Total
0  Renta media por unidad de consumo     Total Nacional     2024  21.759
1  Renta media por unidad de consumo     Total Nacional     2023  20.676
2  Renta media por unidad de consumo     Total Nacional     2022  19.160
3  Renta media por unidad de consumo     Total Nacional     2021  18.103
4  Renta media por unidad de consumo     Total Nacional     2020  18.116

## Tasa de riesgo de pobreza (umbral fijo 2008)

Este indicador mide el porcentaje de población cuya renta se sitúa por debajo de un **umbral de pobreza fijo establecido en 2008**, lo que permite analizar la **evolución del poder adquisitivo real** de los hogares a lo largo del tiempo. Su uso facilita comparaciones temporales sin el efecto de cambios en el umbral relativo, complementando los indicadores de renta, precios y condiciones materiales.

[Bibliografia](https://www.ine.es/jaxiT3/Tabla.htm?t=69366&L=0)

In [24]:
df = pd.read_csv("../../data/raw/Tasa_riesgo_pobreza.csv", sep= ";")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Comunidad autónoma  340 non-null    object
 1   Periodo             340 non-null    int64
 2   Total               340 non-null    object
dtypes: int64(1), object(2)
memory usage: 8.1+ KB

  Comunidad autónoma  Periodo Total
0     Total Nacional     2024  18,7
1     Total Nacional     2023  20,1
2     Total Nacional     2022  20,5
3     Total Nacional     2021  22,8
4     Total Nacional     2020  21,8

## Dificultades para llegar a fin de mes

Este indicador recoge el porcentaje de población que declara tener **algún grado de dificultad para llegar a fin de mes** (con mucha dificultad, con dificultad o con cierta dificultad). Se utiliza como medida sintética de **estrés económico percibido**, complementando los indicadores objetivo

[Bibliografia](https://www.ine.es/jaxiT3/Tabla.htm?t=69461&L=0)

In [25]:
df = pd.read_csv("../../data/raw/Dificultades_llegar_fin_mes.csv", sep =";")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Comunidad autónoma   1260 non-null   object
 1   Nivel de dificultad  1260 non-null   object
 2   Periodo              1260 non-null   int64
 3   Total                1260 non-null   object
dtypes: int64(1), object(3)
memory usage: 39.5+ KB

  Comunidad autónoma   Nivel de dificultad  Periodo Total
0     Total Nacional  Con mucha dificultad     2024   9,1
1     Total Nacional  Con mucha dificultad     2023   9,3
2     Total Nacional  Con mucha dificultad     2022   8,7
3     Total Nacional  Con mucha dificultad     2021   8,8
4     Total Nacional  Con mucha dificultad     2020    10

In [26]:
df['Nivel de dificultad'].unique()

array(['Con mucha dificultad', 'Con dificultad', 'Con cierta dificultad'],
      dtype=object)

## Desigualdad de ingresos (S80/S20)

El indicador S80/S20 mide la desigualdad de ingresos como el cociente entre la renta total del 20 % de la población con mayores ingresos y la del 20 % con menores ingresos. Valores más altos indican mayor desigualdad. Su incorporación permite contextualizar los indicadores de renta y pobreza, aportando una dimensión distributiva al análisis de las condiciones económicas.

PIB ↑ + S80/S20 ↑
→ crecimiento desigual

Renta media ↑ + S80/S20 estable
→ mejora más homogénea

Renta mediana baja + S80/S20 alto
→ desigualdad estructural

[Bibliografia](https://www.ine.es/jaxiT3/Tabla.htm?t=69378&L=0)

In [27]:
df = pd.read_csv("../../data/raw/Desigualdad_S80S20.csv", sep =";")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Comunidad autónoma  340 non-null    object
 1   Periodo             340 non-null    int64
 2   Total               340 non-null    object
dtypes: int64(1), object(2)
memory usage: 8.1+ KB

  Comunidad autónoma  Periodo Total
0     Total Nacional     2024   5,4
1     Total Nacional     2023   5,5
2     Total Nacional     2022   5,6
3     Total Nacional     2021   6,2
4     Total Nacional     2020   5,8

## Incapacidad de hacer frente a gastos económicos imprevistos

Este indicador mide el porcentaje de población que declara no poder afrontar un **gasto económico imprevisto**, y se utiliza como aproximación a la **capacidad de resiliencia financiera** de los hogares. Su incorporación permite complementar los indicadores de renta, pobreza y dificultad económica, aportando una medida directa de vulnerabilidad ante shocks económicos.

[Bibliografia](https://www.ine.es/jaxiT3/Tabla.htm?t=69526&L=0)

In [28]:
df = pd.read_csv("../../data/raw/gastos_imprevistos.csv", sep =";")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Comunidad autónoma  420 non-null    object
 1   Periodo             420 non-null    int64
 2   Total               420 non-null    object
dtypes: int64(1), object(2)
memory usage: 10.0+ KB

  Comunidad autónoma  Periodo Total
0     Total Nacional     2024  35,8
1     Total Nacional     2023  37,1
2     Total Nacional     2022  35,5
3     Total Nacional     2021  33,4
4     Total Nacional     2020  35,4

## Seguridad física y personal

Para aproximar la dimensión de seguridad física y personal se incorpora la **tasa de criminalidad**, que refleja la incidencia de delitos en cada comunidad autónoma. Este indicador se considera más adecuado para el análisis de calidad de vida que la tasa de homicidios, dado que presenta mayor variabilidad territorial y temporal en el contexto español, permitiendo una mejor comparación entre comunidades y a lo largo del tiempo.  
La tasa de criminalidad es un indicador que mide la frecuencia de delitos en relación con la población, para poder comparar territorios con distinto tamaño poblacional (delitos cada 1000 habitantes).

[Bibliografia](https://www.ine.es/jaxiT3/Tabla.htm?t=74615&L=0)

In [29]:
df = pd.read_csv("../../data/raw/tasa_homicidio_criminalidad.csv", sep =";")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 4 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Comunidad autónoma            600 non-null    object
 1   Indicador de calidad de vida  600 non-null    object
 2   Periodo                       600 non-null    int64
 3   Total                         600 non-null    object
dtypes: int64(1), object(3)
memory usage: 18.9+ KB

  Comunidad autónoma Indicador de calidad de vida  Periodo Total
0     Total Nacional         Tasa de criminalidad     2024  50,3
1     Total Nacional         Tasa de criminalidad     2023    51
2     Total Nacional         Tasa de criminalidad     2022  48,6
3     Total Nacional         Tasa de criminalidad     2021  41,3
4     Total Nacional         Tasa de criminalidad     2020  37,3

In [31]:
df['Indicador de calidad de vida'].unique()

array(['Tasa de criminalidad', 'Tasa de homicidios'], dtype=object)