In [8]:
import pandas as pd

In [14]:
df = pd.read_csv('data/processed/dataset_sucio.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 31 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   año                                 266 non-null    int64
 1   com_aut                             266 non-null    object
 2   pib                                 266 non-null    float64
 3   pob                                 266 non-null    float64
 4   sui                                 266 non-null    float64
 5   nat                                 266 non-null    float64
 6   paro                                266 non-null    float64
 7   ing                                 266 non-null    float64
 8   pobr                                152 non-null    float64
 9   fum                                 38 non-null     float64
 10  alc                                 95 non-null     float64
 11  obes                                38 non-null     float64
 12  fyv                                 38 non-null     float64
 13  crim                                234 non-null    float64
 14  homi                                234 non-null    float64
 15  sati                                76 non-null     float64
 16  pib_pc                              266 non-null    float64
 17  renta_pc                            266 non-null    float64
 18  poblacion                           266 non-null    float64
 19  gasto_elevado_vivienda(%)           266 non-null    float64
 20  falta_espacio_vivienda(%)           266 non-null    float64
 21  retrasos_pagos(%)                   266 non-null    float64
 22  renta_media                         266 non-null    float64
 23  renta_mediana                       266 non-null    float64
 24  riesgo_pobreza(%)                   266 non-null    float64
 25  dificultad_fin_mes(%)               266 non-null    float64
 26  desigualdad_ing(S80/S20)            266 non-null    float64
 27  inc_gastos_imprevistos(%)           266 non-null    float64
 28  tasa_criminalidad                   247 non-null    float64
 29  precio_medio_anual_eur_m2_venta     254 non-null    float64
 30  precio_medio_anual_eur_m2_alquiler  254 non-null    float64
dtypes: float64(29), int64(1), object(1)
memory usage: 64.6+ KB

In [15]:
df.isna().sum()

año                                     0
com_aut                                 0
pib                                     0
pob                                     0
sui                                     0
nat                                     0
paro                                    0
ing                                     0
pobr                                  114
fum                                   228
alc                                   171
obes                                  228
fyv                                   228
crim                                   32
homi                                   32
sati                                  190
pib_pc                                  0
renta_pc                                0
poblacion                               0
gasto_elevado_vivienda(%)               0
falta_espacio_vivienda(%)               0
retrasos_pagos(%)                       0
renta_media                             0
renta_mediana                           0
riesgo_pobreza(%)                       0
dificultad_fin_mes(%)                   0
desigualdad_ing(S80/S20)                0
inc_gastos_imprevistos(%)               0
tasa_criminalidad                      19
precio_medio_anual_eur_m2_venta        12
precio_medio_anual_eur_m2_alquiler     12
dtype: int64

In [19]:
df[df['crim'].isna()]

,año,com_aut,pib,pob,sui,nat,paro,ing,pobr,fum,...,retrasos_pagos(%),renta_media,renta_mediana,riesgo_pobreza(%),dificultad_fin_mes(%),desigualdad_ing(S80/S20),inc_gastos_imprevistos(%),tasa_criminalidad,precio_medio_anual_eur_m2_venta,precio_medio_anual_eur_m2_alquiler
0,2009,Andalucía,145802256.0,8244.5,10.87,11.48,17.73,9437.0,NaN,20.93,...,10.6,143930.0,126950.0,27.7,71.8,6.0,45.7,NaN,1757.50,7.27
14,2009,Aragón,33814117.0,1344.5,7.21,9.72,7.29,11963.0,NaN,17.76,...,3.4,185610.0,171930.0,10.4,36.7,4.4,15.4,NaN,1766.33,7.34
28,2009,Asturias,22366414.0,1076.4,9.47,7.63,8.50,12412.0,NaN,19.24,...,5.3,185610.0,160830.0,12.9,50.0,5.1,21.6,NaN,1760.42,8.21
42,2009,Balears,26770420.0,1078.1,8.16,11.17,10.16,11909.0,NaN,20.54,...,18.6,175480.0,153080.0,18.1,62.2,6.3,37.8,NaN,2361.08,10.65
56,2009,Canarias,39505370.0,2034.2,9.72,9.32,17.25,9416.0,NaN,20.69,...,20.8,136120.0,116730.0,29.2,77.5,6.3,60.1,NaN,1686.58,7.91
70,2009,Cantabria,12811684.0,586.8,3.98,9.58,7.16,11736.0,NaN,18.88,...,4.5,181080.0,162120.0,13.4,49.1,5.7,22.0,NaN,1916.17,9.51
84,2009,Castilla - La Mancha,39355657.0,2075.9,7.72,10.75,11.67,9530.0,NaN,20.60,...,12.4,147120.0,129680.0,24.1,62.5,4.9,34.9,NaN,1274.75,5.25
98,2009,Castilla Y León,54452146.0,2547.6,7.87,8.01,9.62,10852.0,NaN,18.98,...,7.2,164150.0,146580.0,18.7,55.4,5.1,24.3,NaN,1373.17,5.29
99,2010,Castilla Y León,54692531.0,2545.4,8.07,8.05,13.98,11590.0,NaN,19.00,...,9.2,1610.0,147360.0,19.0,54.2,5.2,31.4,33.2,1402.33,5.26
100,2011,Castilla Y León,54328993.0,2541.4,7.68,7.82,15.80,11355.0,NaN,NaN,...,7.7,159180.0,144770.0,21.3,49.3,4.9,25.1,33.0,1465.42,5.58
101,2012,Castilla Y León,52589720.0,2525.5,6.49,7.54,16.86,11221.0,NaN,NaN,...,6.6,159090.0,143540.0,20.9,48.6,5.0,28.4,33.4,1395.00,5.59
102,2013,Castilla Y León,51280425.0,2504.7,7.32,7.11,19.80,11230.0,NaN,NaN,...,3.2,157430.0,141620.0,24.2,57.0,5.2,25.3,31.9,1294.00,5.28
103,2014,Castilla Y León,51383670.0,2483.0,7.58,7.20,21.75,11123.0,NaN,NaN,...,4.7,15080.0,137910.0,29.6,55.2,6.2,29.2,31.0,1215.83,5.15
104,2015,Castilla Y León,53183396.0,2462.2,8.76,7.06,20.77,10807.0,25.1,NaN,...,5.3,152840.0,136350.0,25.8,52.7,5.6,26.5,30.3,1172.33,5.22
105,2016,Castilla Y León,54630532.0,2442.3,7.82,6.82,18.26,10998.0,22.3,NaN,...,5.8,156450.0,139870.0,26.7,47.3,5.1,24.1,29.5,1147.83,5.38
106,2017,Castilla Y León,55879293.0,2421.6,7.73,6.40,15.82,11218.0,21.4,NaN,...,2.4,1630.0,150080.0,22.3,39.0,4.7,23.9,29.7,1148.42,5.69
107,2018,Castilla Y León,58326859.0,2408.6,7.97,6.24,14.08,11697.0,18.2,NaN,...,3.2,172640.0,152830.0,20.1,43.1,4.8,23.6,31.1,1159.75,6.02
108,2019,Castilla Y León,59649198.0,2400.5,7.76,5.96,12.10,12474.0,18.7,NaN,...,3.1,172330.0,153490.0,17.0,35.6,4.5,23.9,31.8,1153.58,6.36
109,2020,Castilla Y León,54794589.0,2389.2,7.92,5.71,11.63,12530.0,16.2,NaN,...,6.9,182840.0,16640.0,15.6,34.0,4.5,24.7,27.2,1130.83,6.67
110,2021,Castilla Y León,59465900.0,2376.7,8.19,5.50,12.06,13236.0,18.4,NaN,...,10.0,181810.0,166880.0,19.6,35.2,5.1,24.1,31.1,1135.33,6.85
111,2022,Castilla Y León,65461058.0,2379.6,8.81,5.52,11.61,13258.0,21.9,NaN,...,10.4,191170.0,173370.0,17.8,39.9,4.9,27.1,36.5,1137.92,7.08
112,2009,Cataluña,200745296.0,7447.3,5.84,11.44,8.89,13048.0,NaN,20.91,...,9.0,189780.0,168180.0,14.6,65.5,5.8,38.6,NaN,2316.08,9.77
126,2009,Ceuta,1484372.0,77.8,2.45,14.81,17.43,8537.0,NaN,20.09,...,5.4,142610.0,115740.0,36.4,77.8,15.0,44.8,NaN,NaN,NaN
140,2009,Comunitat Valenciana,101989994.0,4984.4,7.65,10.51,11.99,10310.0,NaN,19.88,...,18.7,157030.0,140040.0,20.4,64.7,5.3,39.3,NaN,1640.50,6.52
154,2009,Extremadura,18370208.0,1097.1,7.19,9.40,15.35,8407.0,NaN,25.32,...,1.8,138330.0,120240.0,29.7,66.7,5.6,30.1,NaN,1148.08,5.32
168,2009,Galicia,56253055.0,2769.1,9.95,8.14,8.64,9764.0,NaN,17.71,...,6.7,151130.0,136070.0,19.2,60.4,4.6,33.6,NaN,1543.83,7.56
182,2009,Madrid,199290149.0,6354.1,2.95,11.95,8.61,13089.0,NaN,17.74,...,12.3,205970.0,183490.0,15.4,56.5,6.3,32.5,NaN,2600.58,11.03
196,2009,Melilla,1361870.0,74.5,10.48,17.09,19.99,12113.0,NaN,15.18,...,13.1,17120.0,186340.0,30.0,67.5,9.9,52.2,NaN,NaN,NaN
210,2009,Murcia,28076274.0,1448.5,8.73,12.82,12.44,9751.0,NaN,23.65,...,18.1,141390.0,124890.0,28.0,74.0,5.7,47.2,NaN,1443.42,6.02
224,2009,Navarra,18001876.0,630.1,8.67,10.86,6.83,13903.0,NaN,18.17,...,7.6,213180.0,189220.0,7.3,39.8,4.7,20.2,NaN,NaN,NaN
238,2009,País Vasco,63601702.0,2177.0,7.52,9.60,6.63,14539.0,NaN,16.09,...,3.8,221380.0,19940.0,9.8,44.8,5.2,22.2,NaN,NaN,NaN
252,2009,Rioja,7911873.0,319.8,8.97,10.41,7.90,11577.0,NaN,18.74,...,11.7,164470.0,141320.0,16.6,55.5,5.1,28.3,NaN,NaN,NaN

In [20]:
df[df['homi'].isna()]

,año,com_aut,pib,pob,sui,nat,paro,ing,pobr,fum,...,retrasos_pagos(%),renta_media,renta_mediana,riesgo_pobreza(%),dificultad_fin_mes(%),desigualdad_ing(S80/S20),inc_gastos_imprevistos(%),tasa_criminalidad,precio_medio_anual_eur_m2_venta,precio_medio_anual_eur_m2_alquiler
0,2009,Andalucía,145802256.0,8244.5,10.87,11.48,17.73,9437.0,NaN,20.93,...,10.6,143930.0,126950.0,27.7,71.8,6.0,45.7,NaN,1757.50,7.27
14,2009,Aragón,33814117.0,1344.5,7.21,9.72,7.29,11963.0,NaN,17.76,...,3.4,185610.0,171930.0,10.4,36.7,4.4,15.4,NaN,1766.33,7.34
28,2009,Asturias,22366414.0,1076.4,9.47,7.63,8.50,12412.0,NaN,19.24,...,5.3,185610.0,160830.0,12.9,50.0,5.1,21.6,NaN,1760.42,8.21
42,2009,Balears,26770420.0,1078.1,8.16,11.17,10.16,11909.0,NaN,20.54,...,18.6,175480.0,153080.0,18.1,62.2,6.3,37.8,NaN,2361.08,10.65
56,2009,Canarias,39505370.0,2034.2,9.72,9.32,17.25,9416.0,NaN,20.69,...,20.8,136120.0,116730.0,29.2,77.5,6.3,60.1,NaN,1686.58,7.91
70,2009,Cantabria,12811684.0,586.8,3.98,9.58,7.16,11736.0,NaN,18.88,...,4.5,181080.0,162120.0,13.4,49.1,5.7,22.0,NaN,1916.17,9.51
84,2009,Castilla - La Mancha,39355657.0,2075.9,7.72,10.75,11.67,9530.0,NaN,20.60,...,12.4,147120.0,129680.0,24.1,62.5,4.9,34.9,NaN,1274.75,5.25
98,2009,Castilla Y León,54452146.0,2547.6,7.87,8.01,9.62,10852.0,NaN,18.98,...,7.2,164150.0,146580.0,18.7,55.4,5.1,24.3,NaN,1373.17,5.29
99,2010,Castilla Y León,54692531.0,2545.4,8.07,8.05,13.98,11590.0,NaN,19.00,...,9.2,1610.0,147360.0,19.0,54.2,5.2,31.4,33.2,1402.33,5.26
100,2011,Castilla Y León,54328993.0,2541.4,7.68,7.82,15.80,11355.0,NaN,NaN,...,7.7,159180.0,144770.0,21.3,49.3,4.9,25.1,33.0,1465.42,5.58
101,2012,Castilla Y León,52589720.0,2525.5,6.49,7.54,16.86,11221.0,NaN,NaN,...,6.6,159090.0,143540.0,20.9,48.6,5.0,28.4,33.4,1395.00,5.59
102,2013,Castilla Y León,51280425.0,2504.7,7.32,7.11,19.80,11230.0,NaN,NaN,...,3.2,157430.0,141620.0,24.2,57.0,5.2,25.3,31.9,1294.00,5.28
103,2014,Castilla Y León,51383670.0,2483.0,7.58,7.20,21.75,11123.0,NaN,NaN,...,4.7,15080.0,137910.0,29.6,55.2,6.2,29.2,31.0,1215.83,5.15
104,2015,Castilla Y León,53183396.0,2462.2,8.76,7.06,20.77,10807.0,25.1,NaN,...,5.3,152840.0,136350.0,25.8,52.7,5.6,26.5,30.3,1172.33,5.22
105,2016,Castilla Y León,54630532.0,2442.3,7.82,6.82,18.26,10998.0,22.3,NaN,...,5.8,156450.0,139870.0,26.7,47.3,5.1,24.1,29.5,1147.83,5.38
106,2017,Castilla Y León,55879293.0,2421.6,7.73,6.40,15.82,11218.0,21.4,NaN,...,2.4,1630.0,150080.0,22.3,39.0,4.7,23.9,29.7,1148.42,5.69
107,2018,Castilla Y León,58326859.0,2408.6,7.97,6.24,14.08,11697.0,18.2,NaN,...,3.2,172640.0,152830.0,20.1,43.1,4.8,23.6,31.1,1159.75,6.02
108,2019,Castilla Y León,59649198.0,2400.5,7.76,5.96,12.10,12474.0,18.7,NaN,...,3.1,172330.0,153490.0,17.0,35.6,4.5,23.9,31.8,1153.58,6.36
109,2020,Castilla Y León,54794589.0,2389.2,7.92,5.71,11.63,12530.0,16.2,NaN,...,6.9,182840.0,16640.0,15.6,34.0,4.5,24.7,27.2,1130.83,6.67
110,2021,Castilla Y León,59465900.0,2376.7,8.19,5.50,12.06,13236.0,18.4,NaN,...,10.0,181810.0,166880.0,19.6,35.2,5.1,24.1,31.1,1135.33,6.85
111,2022,Castilla Y León,65461058.0,2379.6,8.81,5.52,11.61,13258.0,21.9,NaN,...,10.4,191170.0,173370.0,17.8,39.9,4.9,27.1,36.5,1137.92,7.08
112,2009,Cataluña,200745296.0,7447.3,5.84,11.44,8.89,13048.0,NaN,20.91,...,9.0,189780.0,168180.0,14.6,65.5,5.8,38.6,NaN,2316.08,9.77
126,2009,Ceuta,1484372.0,77.8,2.45,14.81,17.43,8537.0,NaN,20.09,...,5.4,142610.0,115740.0,36.4,77.8,15.0,44.8,NaN,NaN,NaN
140,2009,Comunitat Valenciana,101989994.0,4984.4,7.65,10.51,11.99,10310.0,NaN,19.88,...,18.7,157030.0,140040.0,20.4,64.7,5.3,39.3,NaN,1640.50,6.52
154,2009,Extremadura,18370208.0,1097.1,7.19,9.40,15.35,8407.0,NaN,25.32,...,1.8,138330.0,120240.0,29.7,66.7,5.6,30.1,NaN,1148.08,5.32
168,2009,Galicia,56253055.0,2769.1,9.95,8.14,8.64,9764.0,NaN,17.71,...,6.7,151130.0,136070.0,19.2,60.4,4.6,33.6,NaN,1543.83,7.56
182,2009,Madrid,199290149.0,6354.1,2.95,11.95,8.61,13089.0,NaN,17.74,...,12.3,205970.0,183490.0,15.4,56.5,6.3,32.5,NaN,2600.58,11.03
196,2009,Melilla,1361870.0,74.5,10.48,17.09,19.99,12113.0,NaN,15.18,...,13.1,17120.0,186340.0,30.0,67.5,9.9,52.2,NaN,NaN,NaN
210,2009,Murcia,28076274.0,1448.5,8.73,12.82,12.44,9751.0,NaN,23.65,...,18.1,141390.0,124890.0,28.0,74.0,5.7,47.2,NaN,1443.42,6.02
224,2009,Navarra,18001876.0,630.1,8.67,10.86,6.83,13903.0,NaN,18.17,...,7.6,213180.0,189220.0,7.3,39.8,4.7,20.2,NaN,NaN,NaN
238,2009,País Vasco,63601702.0,2177.0,7.52,9.60,6.63,14539.0,NaN,16.09,...,3.8,221380.0,19940.0,9.8,44.8,5.2,22.2,NaN,NaN,NaN
252,2009,Rioja,7911873.0,319.8,8.97,10.41,7.90,11577.0,NaN,18.74,...,11.7,164470.0,141320.0,16.6,55.5,5.1,28.3,NaN,NaN,NaN

In [23]:
df[df['tasa_criminalidad'].isna()]

,año,com_aut,pib,pob,sui,nat,paro,ing,pobr,fum,...,retrasos_pagos(%),renta_media,renta_mediana,riesgo_pobreza(%),dificultad_fin_mes(%),desigualdad_ing(S80/S20),inc_gastos_imprevistos(%),tasa_criminalidad,precio_medio_anual_eur_m2_venta,precio_medio_anual_eur_m2_alquiler
0,2009,Andalucía,145802256.0,8244.5,10.87,11.48,17.73,9437.0,NaN,20.93,...,10.6,143930.0,126950.0,27.7,71.8,6.0,45.7,NaN,1757.50,7.27
14,2009,Aragón,33814117.0,1344.5,7.21,9.72,7.29,11963.0,NaN,17.76,...,3.4,185610.0,171930.0,10.4,36.7,4.4,15.4,NaN,1766.33,7.34
28,2009,Asturias,22366414.0,1076.4,9.47,7.63,8.50,12412.0,NaN,19.24,...,5.3,185610.0,160830.0,12.9,50.0,5.1,21.6,NaN,1760.42,8.21
42,2009,Balears,26770420.0,1078.1,8.16,11.17,10.16,11909.0,NaN,20.54,...,18.6,175480.0,153080.0,18.1,62.2,6.3,37.8,NaN,2361.08,10.65
56,2009,Canarias,39505370.0,2034.2,9.72,9.32,17.25,9416.0,NaN,20.69,...,20.8,136120.0,116730.0,29.2,77.5,6.3,60.1,NaN,1686.58,7.91
70,2009,Cantabria,12811684.0,586.8,3.98,9.58,7.16,11736.0,NaN,18.88,...,4.5,181080.0,162120.0,13.4,49.1,5.7,22.0,NaN,1916.17,9.51
84,2009,Castilla - La Mancha,39355657.0,2075.9,7.72,10.75,11.67,9530.0,NaN,20.60,...,12.4,147120.0,129680.0,24.1,62.5,4.9,34.9,NaN,1274.75,5.25
98,2009,Castilla Y León,54452146.0,2547.6,7.87,8.01,9.62,10852.0,NaN,18.98,...,7.2,164150.0,146580.0,18.7,55.4,5.1,24.3,NaN,1373.17,5.29
112,2009,Cataluña,200745296.0,7447.3,5.84,11.44,8.89,13048.0,NaN,20.91,...,9.0,189780.0,168180.0,14.6,65.5,5.8,38.6,NaN,2316.08,9.77
126,2009,Ceuta,1484372.0,77.8,2.45,14.81,17.43,8537.0,NaN,20.09,...,5.4,142610.0,115740.0,36.4,77.8,15.0,44.8,NaN,NaN,NaN
140,2009,Comunitat Valenciana,101989994.0,4984.4,7.65,10.51,11.99,10310.0,NaN,19.88,...,18.7,157030.0,140040.0,20.4,64.7,5.3,39.3,NaN,1640.50,6.52
154,2009,Extremadura,18370208.0,1097.1,7.19,9.40,15.35,8407.0,NaN,25.32,...,1.8,138330.0,120240.0,29.7,66.7,5.6,30.1,NaN,1148.08,5.32
168,2009,Galicia,56253055.0,2769.1,9.95,8.14,8.64,9764.0,NaN,17.71,...,6.7,151130.0,136070.0,19.2,60.4,4.6,33.6,NaN,1543.83,7.56
182,2009,Madrid,199290149.0,6354.1,2.95,11.95,8.61,13089.0,NaN,17.74,...,12.3,205970.0,183490.0,15.4,56.5,6.3,32.5,NaN,2600.58,11.03
196,2009,Melilla,1361870.0,74.5,10.48,17.09,19.99,12113.0,NaN,15.18,...,13.1,17120.0,186340.0,30.0,67.5,9.9,52.2,NaN,NaN,NaN
210,2009,Murcia,28076274.0,1448.5,8.73,12.82,12.44,9751.0,NaN,23.65,...,18.1,141390.0,124890.0,28.0,74.0,5.7,47.2,NaN,1443.42,6.02
224,2009,Navarra,18001876.0,630.1,8.67,10.86,6.83,13903.0,NaN,18.17,...,7.6,213180.0,189220.0,7.3,39.8,4.7,20.2,NaN,NaN,NaN
238,2009,País Vasco,63601702.0,2177.0,7.52,9.60,6.63,14539.0,NaN,16.09,...,3.8,221380.0,19940.0,9.8,44.8,5.2,22.2,NaN,NaN,NaN
252,2009,Rioja,7911873.0,319.8,8.97,10.41,7.90,11577.0,NaN,18.74,...,11.7,164470.0,141320.0,16.6,55.5,5.1,28.3,NaN,NaN,NaN

In [24]:
df[df['precio_medio_anual_eur_m2_venta'].isna()]

,año,com_aut,pib,pob,sui,nat,paro,ing,pobr,fum,...,retrasos_pagos(%),renta_media,renta_mediana,riesgo_pobreza(%),dificultad_fin_mes(%),desigualdad_ing(S80/S20),inc_gastos_imprevistos(%),tasa_criminalidad,precio_medio_anual_eur_m2_venta,precio_medio_anual_eur_m2_alquiler
126,2009,Ceuta,1484372.0,77.8,2.45,14.81,17.43,8537.0,NaN,20.09,...,5.4,142610.0,115740.0,36.4,77.8,15.0,44.8,NaN,NaN,NaN
127,2010,Ceuta,1494058.0,80.6,10.79,14.79,18.55,9367.0,NaN,9.89,...,13.6,153320.0,132510.0,31.3,78.0,8.3,58.7,74.1,NaN,NaN
137,2020,Ceuta,1535718.0,84.5,4.59,10.04,25.84,10724.0,49.1,NaN,...,28.2,150580.0,124550.0,36.3,42.6,10.7,55.9,43.2,NaN,NaN
138,2021,Ceuta,1634006.0,83.1,5.12,8.68,24.53,10750.0,35.9,NaN,...,29.4,161590.0,123320.0,35.7,53.9,9.5,54.9,47.1,NaN,NaN
139,2022,Ceuta,1768941.0,83.1,5.55,8.77,30.85,11305.0,40.5,NaN,...,24.1,188640.0,14750.0,34.8,60.3,11.0,47.0,43.9,NaN,NaN
196,2009,Melilla,1361870.0,74.5,10.48,17.09,19.99,12113.0,NaN,15.18,...,13.1,17120.0,186340.0,30.0,67.5,9.9,52.2,NaN,NaN,NaN
197,2010,Melilla,1367400.0,77.4,8.20,17.55,23.49,12370.0,NaN,11.24,...,22.8,182590.0,171980.0,25.8,69.3,7.6,53.2,60.1,NaN,NaN
198,2011,Melilla,1374489.0,80.2,0.97,18.15,22.78,12474.0,NaN,NaN,...,18.8,182780.0,14320.0,27.2,81.4,10.7,52.0,61.6,NaN,NaN
199,2012,Melilla,1325903.0,82.7,6.61,18.34,22.39,13274.0,NaN,NaN,...,4.3,190110.0,148470.0,12.0,60.3,5.4,55.5,56.1,NaN,NaN
224,2009,Navarra,18001876.0,630.1,8.67,10.86,6.83,13903.0,NaN,18.17,...,7.6,213180.0,189220.0,7.3,39.8,4.7,20.2,NaN,NaN,NaN
238,2009,País Vasco,63601702.0,2177.0,7.52,9.60,6.63,14539.0,NaN,16.09,...,3.8,221380.0,19940.0,9.8,44.8,5.2,22.2,NaN,NaN,NaN
252,2009,Rioja,7911873.0,319.8,8.97,10.41,7.90,11577.0,NaN,18.74,...,11.7,164470.0,141320.0,16.6,55.5,5.1,28.3,NaN,NaN,NaN

In [25]:
df[df['precio_medio_anual_eur_m2_alquiler'].isna()]

,año,com_aut,pib,pob,sui,nat,paro,ing,pobr,fum,...,retrasos_pagos(%),renta_media,renta_mediana,riesgo_pobreza(%),dificultad_fin_mes(%),desigualdad_ing(S80/S20),inc_gastos_imprevistos(%),tasa_criminalidad,precio_medio_anual_eur_m2_venta,precio_medio_anual_eur_m2_alquiler
126,2009,Ceuta,1484372.0,77.8,2.45,14.81,17.43,8537.0,NaN,20.09,...,5.4,142610.0,115740.0,36.4,77.8,15.0,44.8,NaN,NaN,NaN
127,2010,Ceuta,1494058.0,80.6,10.79,14.79,18.55,9367.0,NaN,9.89,...,13.6,153320.0,132510.0,31.3,78.0,8.3,58.7,74.1,NaN,NaN
137,2020,Ceuta,1535718.0,84.5,4.59,10.04,25.84,10724.0,49.1,NaN,...,28.2,150580.0,124550.0,36.3,42.6,10.7,55.9,43.2,NaN,NaN
138,2021,Ceuta,1634006.0,83.1,5.12,8.68,24.53,10750.0,35.9,NaN,...,29.4,161590.0,123320.0,35.7,53.9,9.5,54.9,47.1,NaN,NaN
139,2022,Ceuta,1768941.0,83.1,5.55,8.77,30.85,11305.0,40.5,NaN,...,24.1,188640.0,14750.0,34.8,60.3,11.0,47.0,43.9,NaN,NaN
196,2009,Melilla,1361870.0,74.5,10.48,17.09,19.99,12113.0,NaN,15.18,...,13.1,17120.0,186340.0,30.0,67.5,9.9,52.2,NaN,NaN,NaN
197,2010,Melilla,1367400.0,77.4,8.20,17.55,23.49,12370.0,NaN,11.24,...,22.8,182590.0,171980.0,25.8,69.3,7.6,53.2,60.1,NaN,NaN
198,2011,Melilla,1374489.0,80.2,0.97,18.15,22.78,12474.0,NaN,NaN,...,18.8,182780.0,14320.0,27.2,81.4,10.7,52.0,61.6,NaN,NaN
199,2012,Melilla,1325903.0,82.7,6.61,18.34,22.39,13274.0,NaN,NaN,...,4.3,190110.0,148470.0,12.0,60.3,5.4,55.5,56.1,NaN,NaN
224,2009,Navarra,18001876.0,630.1,8.67,10.86,6.83,13903.0,NaN,18.17,...,7.6,213180.0,189220.0,7.3,39.8,4.7,20.2,NaN,NaN,NaN
238,2009,País Vasco,63601702.0,2177.0,7.52,9.60,6.63,14539.0,NaN,16.09,...,3.8,221380.0,19940.0,9.8,44.8,5.2,22.2,NaN,NaN,NaN
252,2009,Rioja,7911873.0,319.8,8.97,10.41,7.90,11577.0,NaN,18.74,...,11.7,164470.0,141320.0,16.6,55.5,5.1,28.3,NaN,NaN,NaN

**La importancia incial se mide clasificándolas en target/directora (0), agrupación importante (1), agrupación interesante (2), agrupación secundaria (3)**  
0 (directoras): estructuran el análisis temporal y territorial.  
1 (núcleo): variables económicas y de bienestar directamente relacionadas con el PIB.  
2 (impacto social): reflejan consecuencias o mediadores del nivel económico.

| Variable | Descripción | Tipo de variable | Importancia inicial |
|--------|------------|-----------------|---------------------|
| año | Año de referencia de los datos. | Numérica discreta | 0 |
| com_aut | Comunidad Autónoma de España. | Categórica nominal | 0 |
| pib | Producto Interior Bruto. Valor económico agregado. | Numérica continua | 0 |
| pob | Población total de la comunidad. | Numérica discreta | 3 |
| sui | Tasa de suicidios. Defunciones por suicidio por 100.000 habitantes. | Numérica continua | 2 |
| nat | Tasa de natalidad. Nacimientos por cada 1.000 habitantes. | Numérica continua | 2 |
| paro | Tasa de desempleo. Parados sobre población activa. | Numérica continua | 1 |
| ing | Ingresos medios por persona adulta. | Numérica continua | 1 |
| pobr | Tasa de riesgo de pobreza. | Numérica continua | 1 |
| fum | Porcentaje de población adulta fumadora. | Numérica continua | 3 |
| alc | Porcentaje de población adulta con consumo de riesgo de alcohol. | Numérica continua | 3 |
| obes | Porcentaje de población adulta con obesidad. | Numérica continua | 3 |
| fyv | Porcentaje de población con consumo diario de frutas y verduras. | Numérica continua | 3 |
| crim | Tasa de criminalidad. Infracciones penales por 1.000 habitantes. | Numérica continua | 2 |
| homi | Tasa de homicidios. Homicidios y asesinatos por 100.000 habitantes. | Numérica continua | 3 |
| sati | Nivel de satisfacción general con la vida. | Numérica continua | 1 |
| pib_pc | PIB per cápita a precios de mercado. | Numérica continua | 1 |
| renta_pc | Renta disponible bruta de los hogares per cápita. | Numérica continua | 1 |
| poblacion | Número total de habitantes por comunidad y año. | Numérica discreta | 3 |
| gasto_elevado_vivienda(%) | Porcentaje de población con gasto elevado en vivienda. | Numérica continua | 2 |
| falta_espacio_vivienda(%) | Porcentaje de población que vive en viviendas con falta de espacio. | Numérica continua | 3 |
| retrasos_pagos(%) | Porcentaje de población con retrasos en pagos de vivienda o suministros. | Numérica continua | 2 |
| renta_media | Renta media por unidad de consumo. | Numérica continua | 1 |
| renta_mediana | Renta mediana por unidad de consumo. | Numérica continua | 1 |
| riesgo_pobreza(%) | Porcentaje de población en riesgo de pobreza. | Numérica continua | 1 |
| dificultad_fin_mes(%) | Porcentaje de población con dificultad para llegar a fin de mes. | Numérica continua | 2 |
| desigualdad_ing(S80/S20) | Cociente de desigualdad entre el 20% más rico y el 20% más pobre. | Numérica continua | 1 |
| inc_gastos_imprevistos(%) | Porcentaje de población que no puede afrontar gastos imprevistos. | Numérica continua | 2 |
| tasa_criminalidad | Delitos registrados por cada 1.000 habitantes. | Numérica continua | 2 |
| precio_medio_anual_eur_m2_venta | Precio medio anual de vivienda en venta por m² (€). | Numérica continua | 2 |
| precio_medio_anual_eur_m2_alquiler | Precio medio anual de vivienda en alquiler por m² (€). | Numérica continua | 2 |